---
- name: Provision EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Provision EC2 instance
      amazon.aws.ec2:
        key_name: "{{ aws_key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        wait: yes
        region: "{{ aws_region }}"
        count: "{{ instance_count }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_groups: "{{ security_groups }}"
        assign_public_ip: yes
        aws_access_key: "{{ vault_aws_access_key }}"
        aws_secret_key: "{{ vault_aws_secret_key }}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: provisioned
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      loop: "{{ ec2.instances }}"

