---
- name: Execute All Playbooks
  hosts: localhost
  gather_facts: no
  tasks:
    - import_playbook: provision.yml
    - import_playbook: setup.yml
    - import_playbook: nginx.yml
    - import_playbook: git.yml

