---
- name: Execute All Playbooks
  hosts: localhost
  gather_facts: no
  tasks:
    - import_playbook: provision.yml
    - import_playbook: setup.yml
    - import_playbook: git.yml
    - import_playbook: web_server.yml

